/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const WebsiteId = IDL.Nat;
export const Website = IDL.Record({
  'id' : WebsiteId,
  'url' : IDL.Text,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'submittedAt' : IDL.Int,
  'description' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllWebsites' : IDL.Func([], [IDL.Vec(Website)], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getWebsiteById' : IDL.Func([WebsiteId], [IDL.Opt(Website)], ['query']),
  'searchWebsites' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Vec(Website)],
      ['query'],
    ),
  'submitWebsite' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [Website],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const WebsiteId = IDL.Nat;
  const Website = IDL.Record({
    'id' : WebsiteId,
    'url' : IDL.Text,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'submittedAt' : IDL.Int,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllWebsites' : IDL.Func([], [IDL.Vec(Website)], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getWebsiteById' : IDL.Func([WebsiteId], [IDL.Opt(Website)], ['query']),
    'searchWebsites' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Vec(Website)],
        ['query'],
      ),
    'submitWebsite' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [Website],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };